// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnJcISRBr4sBw52X2Ms_1LNPXS_sk2PsE',
    appId: '1:814014160691:android:9d696f73e4655223bda846',
    messagingSenderId: '814014160691',
    projectId: 'projectcapstone-123123',
    databaseURL: 'https://projectcapstone-123123-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectcapstone-123123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhMFoeZdguR0Mf64tEX83O1FuR5sWHxh8',
    appId: '1:814014160691:ios:f8362a14c19adb80bda846',
    messagingSenderId: '814014160691',
    projectId: 'projectcapstone-123123',
    databaseURL: 'https://projectcapstone-123123-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectcapstone-123123.appspot.com',
    iosClientId: '814014160691-vm38pvdbk5jplaupetb10hkkpsjf6u3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.walletFlutter',
  );
}
